    
from django.core.exceptions import ValidationError
from versatileimagefield.validators import validate_ppoi
